### ISSUE TITLE
Missing the package: composer req friendsoftypo3/headless_powermail

### ISSUE THREAD

**Issue by meincms** [TYPO3-Initiatives/headless_powermail#2]
Package seems to be not available. Any suggestion?
 
[**InvalidArgumentException**]                                                                                                                 
  Could **not** find a matching version of package friendsoftypo3/headless_powermail. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).  
![image](https://user-images.githubusercontent.com/2609699/100234027-ca0e5180-2f2a-11eb-9a05-2859f8f25a8c.png)

**Comment by tmotyl** [comment]
hi @meincms 
good catch, let me add it to packagist

**Comment by tmotyl** [comment]
here you go: https://packagist.org/packages/friendsoftypo3/headless_powermail
