### ISSUE TITLE
Validating / Processing of required fields fails

### ISSUE THREAD

**Issue by SirZockholm** [TYPO3-Initiatives/headless_powermail#3]
Hello friends!

We have a form which does send it's data back to the CMS. I checked this in the "Network" Tab of the Browser-Inspector.
The response of the CMS however is odd. It sends back the form with all data EXCEPT the required ones.

I haven't developed the site myself, I'm just supporting but I can't see any changes in the extensions "powermail" "headless" nor "headless_powermail"...

We're using:
powermail - 7.0
headless - 2.3.0
headless_powermail - dev.master b7186ca

Do you maybe have an idea where the data goes missing?
If you'd need more info please just let me know.

ZH

**Comment by lukaszuznanski** [comment]
What do you mean that i sends back the form? I guess some PHP debugging is required here

**Comment by SirZockholm** [comment]
Hi Lukas.
Sorry for getting back so late. Work is killin' me lately.
We were able to fix the issue. With PHP debugging we noticed the data powermail recieved was empty and in a wrong variable. Basically the problem sat in front of the screen. (me)

Hope you have a great day / weekend

ZH
